org: anishkini007
app: dynamoget
service: dynamoget
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-crudtable-${sls:stage}
  

  environment:
    DYNAMODB_CRUD_TABLE: ${self:service}-crudtable-${sls:stage}
  

functions:
  create:
    handler: create.create
    events:
      - httpApi:
          path: /
          method: post

  get:
    handler: get.get
    events: 
      - httpApi:
          path: /
          method: get

  delete:
    handler: delete.delete
    events:
      - httpApi:
          path: /
          method: delete

  update:
    handler: update.update
    events:
      - httpApi:
          path: /
          method: put

resources:
  Resources:
    crudtable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-crudtable-${sls:stage}

